### ISSUE TITLE
TreeID for SMB2 can be a zero value.

### ISSUE THREAD

**Issue by MikSwens** [IdentityAutomation/vfs-jcifs-ng#1]
I was working with a client using this package with the IBM i NetServer CIFS server.  It was failing on every connection saying that the tree id was invalid.  The jcifs.internal.smb1.com.SmbComTreeConnectAndXResponse class has it right, the tree id can be anything except 0xFFFF.  That hasn't changed with newer SMB dialects.  Modifying jcifs.internal.smb2.tree.Smb2TreeConnectResponse.isValidTid() method to 
return getTreeId() != 0xFFFF;
resolves the issue.

If I were more skilled at using Git, I would create a branch, etc. but my skills with Git are seriously lacking.

**Comment by svella-at-nice** [comment]
@MikSwens The code you are referencing is actually part of the [jcifs-ng](https://github.com/AgNO3/jcifs-ng) project which this project depends on and It appears that it was fixed about a month ago by https://github.com/AgNO3/jcifs-ng/issues/303, though it appears it has not yet been included in a public release build on maven-central.

**Comment by svella** [comment]
@MikSwens The code you are referencing is actually part of the [jcifs-ng](https://github.com/AgNO3/jcifs-ng) project which this project depends on and It appears that it was fixed about a month ago by https://github.com/AgNO3/jcifs-ng/issues/303, though it appears it has not yet been included in a public release build on maven-central.
